### ISSUE TITLE
Storing and hashing old root hashes

### ISSUE THREAD

**Issue by Jasleen1** [facebook/akd#209]
We likely want to have a way to access old root node hashes, even after a tree is updated. For example, at the moment the tests which require multiple root hashes need to obtain the hash for a particular `publish` before the next call to `publish`. Additionally, we probably want to support chaining the hashes together, although this is up for debate.

**Comment by eozturk1** [comment]
@Jasleen1, I thought this was done but I see that the epoch used [here](https://github.com/novifinancial/akd/blob/eda6c3e575419a066db0f32ba3387fc0733388b9/akd/src/append_only_zks.rs#L465) is not right. Could you take a look?
