### ISSUE TITLE
Issue with preload logic

### ISSUE THREAD

**Issue by kevinlewi** [facebook/akd#318]
This check is backwards. Given that this isn't used to "continue" any longer, and instead filters, then this shouldn't be a NOT.

_Originally posted by @dillonrg in https://github.com/facebook/akd/pull/312#discussion_r1059143656_

**Comment by dillonrg** [comment]
The core bug has been identified and fixed with #320. However, verification of the fix was done manually. We'd also like to implement some automated tests to ensure that this issue does not pop up again.
