### ISSUE TITLE
Consider dropping support for the akd_client library

### ISSUE THREAD

**Issue by kevinlewi** [facebook/akd#388]
Or at least moving it under akd_core/ (without the wasm bindings). The reason being that the library is lightweight enough on its own (really just a cosmetic wrapper around akd_core), and once we start adding more customizations like domain separation based on application, the likelihood that someone will want to use akd_client as-is diminishes.

**Comment by slawlor** [comment]
Yeah we could drop it, we'll just need to move some documentation around on how to use `akd_core` as it sits now, it's meant to not be publicly interact-able (i.e. it was supposed to be pretty internal). `akd_client` however does seem to re-export everything, so I agree it's value is limited. We could also move the wasm bindings to an example (unpublished) crate.
